apiVersion: v1
kind: Pod
metadata:
  name: postinstall-hook
  annotations: 
    "helm.sh/hook": "post-install"
spec: 
  containers:
  - name: hook2-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The post-install hook Pod is running & sleep 10']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0

